name: 🚀 Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yusancky/setup-typst@v2
        with:
            version: latest
      - name: Compile the manual
        run: typst compile physica-manual.typ
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
            name: Physica ${{ github.ref_name }}
            files: physica-manual.pdf
            fail_on_unmatched_files: true
      - name: Generate the job summary
        run: echo '🎉 [Release ${{ steps.release.outputs.id }}](${{ steps.release.outputs.upload_url }}) is ready.' >> $GITHUB_STEP_SUMMARY
